version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: builder
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: production-stage
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
