# Generated by Django 5.2 on 2025-04-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngestSensorData',
            new_name='SensorData',
        ),
    ]
